In [7]:
# %timeit sum(range(10000))
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
%timeit sum(range(10000))

166 µs ± 2.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
# Reshape method is used to change the dimensions of the given array
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## SCALAR OPERATION

In [20]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [27]:
# Concatenate fxn
# It joins the given array along the given axis
# The axis has to be consistent with the array to be joined

c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d), axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [28]:
c=np.arange(6).reshape(2,3)
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5


In [48]:
print(np.where(c%2==0,0,c))
print(np.array_split(np.arange(8),3))

[[0 1 0]
 [3 0 5]]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


In [53]:
# wap to find the indices where elements of 2 arrays match
print(np.where(np.array([1, 2, 3, 4, 5])==np.array([5, 2, 3, 7, 5])))

(array([1, 2, 4], dtype=int64),)


In [60]:
# wap to create 5*2 int matrix from a range btwn 100,200 such that diff btwn element is 10
print(np.arange(100,200,10).reshape(5,2))

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [69]:
# case1: sort array by 2nd row
# case2: sort the array by 2nd col
arr = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 63]])
print(arr[:,arr[1, :].argsort()])
print(arr[arr[:, 1].argsort()])

[[73 43 34]
 [12 22 82]
 [63 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 63]]
